
package mypackage;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DilbertSoap", targetNamespace = "http://gcomputer.net/webservices/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DilbertSoap {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "TodaysDilbert", action = "http://gcomputer.net/webservices/TodaysDilbert")
    @WebResult(name = "TodaysDilbertResult", targetNamespace = "http://gcomputer.net/webservices/")
    @RequestWrapper(localName = "TodaysDilbert", targetNamespace = "http://gcomputer.net/webservices/", className = "mypackage.TodaysDilbert")
    @ResponseWrapper(localName = "TodaysDilbertResponse", targetNamespace = "http://gcomputer.net/webservices/", className = "mypackage.TodaysDilbertResponse")
    public String todaysDilbert();

    /**
     * 
     * @param aDate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DailyDilbert", action = "http://gcomputer.net/webservices/DailyDilbert")
    @WebResult(name = "DailyDilbertResult", targetNamespace = "http://gcomputer.net/webservices/")
    @RequestWrapper(localName = "DailyDilbert", targetNamespace = "http://gcomputer.net/webservices/", className = "mypackage.DailyDilbert")
    @ResponseWrapper(localName = "DailyDilbertResponse", targetNamespace = "http://gcomputer.net/webservices/", className = "mypackage.DailyDilbertResponse")
    public String dailyDilbert(
        @WebParam(name = "ADate", targetNamespace = "http://gcomputer.net/webservices/")
        XMLGregorianCalendar aDate);

}
