
package mypackage;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Dilbert", targetNamespace = "http://gcomputer.net/webservices/", wsdlLocation = "http://www.gcomputer.net/webservices/dilbert.asmx?WSDL")
public class Dilbert
    extends Service
{

    private final static URL DILBERT_WSDL_LOCATION;
    private final static WebServiceException DILBERT_EXCEPTION;
    private final static QName DILBERT_QNAME = new QName("http://gcomputer.net/webservices/", "Dilbert");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www.gcomputer.net/webservices/dilbert.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DILBERT_WSDL_LOCATION = url;
        DILBERT_EXCEPTION = e;
    }

    public Dilbert() {
        super(__getWsdlLocation(), DILBERT_QNAME);
    }

    public Dilbert(WebServiceFeature... features) {
        super(__getWsdlLocation(), DILBERT_QNAME, features);
    }

    public Dilbert(URL wsdlLocation) {
        super(wsdlLocation, DILBERT_QNAME);
    }

    public Dilbert(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DILBERT_QNAME, features);
    }

    public Dilbert(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Dilbert(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DilbertSoap
     */
    @WebEndpoint(name = "DilbertSoap")
    public DilbertSoap getDilbertSoap() {
        return super.getPort(new QName("http://gcomputer.net/webservices/", "DilbertSoap"), DilbertSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DilbertSoap
     */
    @WebEndpoint(name = "DilbertSoap")
    public DilbertSoap getDilbertSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://gcomputer.net/webservices/", "DilbertSoap"), DilbertSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns DilbertSoap
     */
    @WebEndpoint(name = "DilbertSoap12")
    public DilbertSoap getDilbertSoap12() {
        return super.getPort(new QName("http://gcomputer.net/webservices/", "DilbertSoap12"), DilbertSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DilbertSoap
     */
    @WebEndpoint(name = "DilbertSoap12")
    public DilbertSoap getDilbertSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://gcomputer.net/webservices/", "DilbertSoap12"), DilbertSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DILBERT_EXCEPTION!= null) {
            throw DILBERT_EXCEPTION;
        }
        return DILBERT_WSDL_LOCATION;
    }

}
